### ISSUE TITLE
Using from generic code—perhaps add an API variant with relaxed type constraints?

### ISSUE THREAD

**Issue by binki** [arogozine/EnumUtilities#7] opened 2015-12-23 05:42 UTC
I read the [Usage with Generics](https://github.com/arogozine/EnumUtilities/tree/d04bb7b0cfcf94e452878f5c46f6c7225804fe0c#usage-with-generics). Basically, to call into `EnumUtil` with client code which has an enum specified via a template, it seems like this code has to be written:

```
public static void ContrivedMethod<E, T>(T value)
where T : struct, E
where E : class, IComparable, IFormattable, IConvertible
{
    Console.WriteLine(
        EnumUtilBase<E>.GetName(value));
}
```

Having to define a method like this has the following disadvantages:
1. The type parameters must be explicitly provided in each call because there’s no method parameter from which `E` may be inferred.
2. This ends up not being safe anyway because it is up to the caller to supply `Enum`—there are no protections against the caller providing something else. So such a method would have to be documented with the same sort of warning that `EnumUtilBase` has and avoided if possible.

This would be OK if the method which has to directly call through `EnumUtilBase<E>` could somehow not rely on its caller supplying `Enum` as a type parameter. But because of how type constraints work, `Enum` _has_ to be supplied explicitly in every place where `T` is explicitly written. If every call to a method which happens to use EnumUtilities for enum manipulation has to know to provide `Enum` and has to be trusted to actually do that, a bigger problem is created and more pointless code is written. And since `T` cannot be inferred, then there’s even more pointless code proliferation and even room for the caller to provide the wrong type parameter and cause different errors.

The way that the `EnumUtil` static class manages to support type inference while using the type constraint system to disallow non-enum types is quite nifty. It is reassuring to know that calls into this API will run fine if the compiler accepts it.

I think that one aspect of EnumUtilities’s type safety feature is exemplified by its wrapper around [`Enum.GetValues()`](https://msdn.microsoft.com/en-us/library/system.enum.getvalues%28v=vs.110%29.aspx). I don’t think the .net framework provides an equivalent that accepts the enum type as a generic type parameter or returns a typed collection of values, resulting in ugly code like `foreach (MyEnum value in Enum.GetValues(typeof(MyEnum)));` rather than `foreach (var value in EnumUtil.GetValues<MyEnum>());`. IMO, just providing such an API without the compiletime enforcement that `MyEnum` be an enum type would still be useful even if the API might throw an `InvalidArgumentException` at runtime when `MyEnum` really isn’t an enum because it would hide the dirtiness of using the .net-provided untyped API.

The following are examples of when I’d like to be able to use an API with relaxed type constraints:
## Extension Methods

If I want to write an extension method which, with the help of type inference, accepts an enum value in a mostly type-safe way, the generic base class trick used by `EnumUtil` itself cannot be used.

```
using EnumUtilities;
using System;

// error CS1106: Extension method must be defined in a non-generic static class
public static class Extensions<E>
where E : class, IComparable, IFormattable, IConvertible
{
    public static void PrintName<T>(this T value)
    where T : struct, E
    {
        Console.WriteLine(EnumUtilBase<E>.GetName(value));
    }
}

// error CS0713: Static class 'Extensions' cannot derive from type 'Extensions<Enum>'. Static classes must derive from object.
public static class Extensions : Extensions<Enum>
{
}
```

So the only option for producing extension methods which use EnumUtilities in their implementation is to require the caller to supply Enum at that point. This would result in calls like `anEnumValue.Print<Enum, SpecificEnumType>()` instead of `anEnumValue.print()`. I can’t think of any way to work around restrictions like this in this sort of scenario.

I figure this is even why EnumUtilties itsself doesn’t provide extension methods at all. This might just be an insurmountable limitation of C#. I guess if the documentation told me I shouldn’t even think about trying this, I might waste less time trying to make it work ;-).
## Generic Classes

If I have a class which takes an enum type parameter, the generic instantiation of that class will have to provide `Enum` and all calls for values with a type matching the provided type parameter will have to go through `EnumUtilBase`. This is probably clear without an example, but:

```
using EnumUtilities;
using System;
using System.Collections;
using System.Collections.Generic;

class EnumEnumerable<E, T> : IEnumerable<T>
where E : class, IComparable, IFormattable, IConvertible
where T : struct, E
{
    public IEnumerator<T> GetEnumerator()
        => ((IList<T>)EnumUtilBase<E>.GetValues<T>()).GetEnumerator();

    IEnumerator IEnumerable.GetEnumerator()
        => GetEnumerator();
}

class EnumEnumerable<E>
where E : class, IComparable, IFormattable, IConvertible
{
    public static EnumEnumerable<E, T> Create<T>()
        where T : struct, E
        => new EnumEnumerable<E, T>();

    // Inference works even though it doesn’t make sense with this particular class:
    public static EnumEnumerable<E, T> Create<T>(T exampleValue)
        where T : struct, E
        => Create<T>();
}

// Allow code like “EnumEnumerable.Create<MyEnum>()” or “EnumEnumerable.Create(MyEnum.Value)”
class EnumEnumerable : EnumEnumerable<Enum>
{
}
```

To use that class itself, calling `EnumEnumerable.Create<MyEnum>()` isn’t a big deal. But when subclassing `EnumEnumerable<E, T>`, this all has to be done again for that subclass specifically. Actually, now that I’m thinking about this, having to do this for subclasses isn’t _too_ awful. While it's a big pain, I guess C# isn’t preventing the [`Create()` type inference pattern](https://msdn.microsoft.com/en-us/library/dd384265%28v=vs.110%29.aspx) from being used here.
# Conclusion

It’d be nice to be able to use EnumUtilities in places where its constraints cannot be satisfied, especially when writing generic extension methods. While `EnumUtilBase<E>` makes writing extensions methods possible, these extension methods are unusable because they cannot use type inference because `Enum` has to be passed in. However, it’s also nice/nifty to have the current `EnumUtil` API which provides compiler-enforced safety. I think that is a feature which is worth keeping.

Perhaps a new static class with a different name and relaxed type constraints could be introduced? Perhaps `UnsafeEnumUtil` which would _not_ require the `E` parameter and only have the constraint `where T : struct, IComparable, IFormattable, IConvertible`? Or is there maybe some hack I haven’t thought of which would let me write extension methods the way I’d like to be able to? Or maybe instead I just have to give up on writing extension methods for enum values and just provide utility static classes?

Sorry for the long read. I wrote a lot just for my own sake to record my journey in experimentation with EnumUtilities and generics so that I don’t end up redoing it in the future.

**Comment by arogozine** [comment] 2015-12-24 18:41
The problem is that you can't really have a generic constraint of enumeration in C#.
Partly because CLR support is lacking, read the discussion here: https://github.com/dotnet/roslyn/issues/262
`EnumUtil<T>` is the best you are going to get.
It is just not usable in C# ... more on that and the end.

In theory you can pass in other types of generic arguments, but in practice I can't think of any types that you can pass in to match the constraint requirements aside from `Enum`
The constraint ensures that the type passed in is both a class and a struct - there are not many of those.
Obviously there is `ValueType` (`Enum` extends it),
For ex,

``` csharp
int intOne = 1;
ValueType intOneV = intOne;
```

but `ValueType` by itself does not have the required interfaces.
If there are any, that is bad, and needs documenting.

Your issue comes down to requiring two, redundant, generic constraints for all the generic call tree.
I am reluctant to add a completely unsafe version of EnumUtil for a sake of simpler generic constrains in implementing code.  

You might want to consider F# for your code. Looks like F# will allow you to consume `EnumUtil` in a generic context (needs testing). Ex,

``` fsharp
let test<'a when 'a : (new : unit -> 'a) and 'a : struct and 'a :> Enum>() = 
    EnumUtil.HasFlagsAttribute<'a>()
```

Also F# is a lot less verbose / cleaner.

**Comment by binki** [comment] 2015-12-29 22:18
Hmm, I am interested in playing with F# to see how its constraints make it work for this scenario, but haven’t gotten to it yet.

I still really want to be able to write generic code that can be applied to various enum types and still take advantage of the sort of APIs EnumUtilities offers. I’m not sure if I should suggest something like this because it would really sort of make things messy just to make up for shortcomings in C#, but what if enum values could be wrapped in a class like `EnumValue<T>` which would provide all of the static methods that `EnumUtil` provides just as member methods? Then I could do something like:

```
void MyGenericMethod<T>(EnumValue<T> value)
{
    foreach (T potentialFlagValue in value.GetValues())
        if (value.HasFlag(potentialFlagValue))
            Console.WriteLine(value.GetName(potentialFlagValue));

    // Unwrapping is possible, but for most things you’d do in generic helper method
    // you probably won’t need to.
    T raw = value.Value;

    // And for completeness should be able to re-wrap a value?
    var thing = value.Wrap(raw);
}

// Call example. This is the gross part—all calls would need to
// wrap the raw enum value in the class.
MyGenericMethod(EnumUtils.Wrap(MyEnum.Flag1|MyEnum.Flag3));
```

I have mashed the concepts of _enum type inspector_ and _enum value inspector_ together into one class (e.g., `GetValues()` ignores the actual value but just uses the enum’s type information and `HasFlag()` actually uses the current value). They could be separated into different classes if that’s cleaner/less confusing.

Enforcement of a value being an Enum would be done through EnumUtils.Wrap() because EnumUtils has the magical Enum type constraint. I.e., you wouldn’t just be able to cast an int directly to an `EnumValue<T>`, so I think this would preserve the type safety goal.

From a performance perspective, if a class had a lot of enum properties and it was a generic class meant to be subclassed by other code and there would be a lot of instances of it, it might be easier for the author to just store `EnumValue<T>` instances as the properties instead of pure `T`. I’m not sure that shoudl be considered a valid use case, but if it is then `EnumValue<T>` should be a struct instead of a class so that it can be stored efficiently directly within the class it is being contained in.

I would like this and use it myself because I would be able to write generic methods and use EnumUtilities’s generic typesafe API because I think it is worth it. But it would be clunky to use. But, your thoughts on this sort of approach? ;-)

**Comment by arogozine** [comment] 2016-01-04 23:37
The idea is nice - definitely not something I'd have thought up. One issue is that the wrapper would need to be updated each time a new static function gets added to `EnumUtilBase`. The other issue is the performance hit of wrappers.

Weighing the options, having an `EnumUtilUnsafe` (that has no constraints for `E`) and marking it as `EditorBrowsable.Never` may actually be the best choice.

**Closed as completed** 2016-03-23 05:15 UTC

**Comment by binki** [comment] 2016-07-21 22:15
Thanks, that works. It’s really nice to be able to use `EnumUtilUnsafe` from within extension methods!
